### ISSUE TITLE
--push-p12-path parameter removed for turtle build:ios in [0.5.0]

### ISSUE THREAD

**Issue by fredriksebek** [expo/turtle#14]
Thank you for doing such an awesome job with turtle! It is super nice to be able to build the standalone files locally. 

I have a quick issue (question) regarding the --push-p12-path parameter that was recently removed. I currently have three different applications, which each have their own different push notification certificate.  This causes a slight inconvenience when deploying each respective application since their is no way to set the push certificate in a convenient way (expo cli doesn't have a setter for the push notification certificate). Currently expo build:ios -c, seems to be the only alternative, however the irony is that it will start the build process externally, and it requires all the other certificates to be provided as well.

Would it be possible to add the flag back into the api?

**Comment by dsokal** [comment]
Hey @fredriksebek,
the `--push-p12-path` parameter was removed from `turtle-cli` because it was never used in the code. Feel free to check the codebase yourself. Push notification certificates are identified by bundle identifier on our server. This means you can't use 3 different certificates for 3 different builds under the same bundle identifier. This also means you just need to run `expo build:ios` once for each app/bundle identifier (to generate or to set the appropriate certificates) and you don't need to run it over and over again.
However, we're aware of that there isn't a simple way of uploading a push notification certificate separately from other Apple credentials. Recently, I've been working on a new feature in `expo-cli` - generating push notification keys (which could be shared across different apps) instead of push notification certificates - my pull request (https://github.com/expo/expo-cli/pull/303) should be merged soon.
