### ISSUE TITLE
Support JDK 13, or >8 in general

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [expo/turtle#190]
#### Motivation Behind Feature
Supporting JDK 13, the latest and greatest, sounds nice, yes?

#### Feature Description
Right now `turtle-cli` manually checks for version 8. Could any bugs preventing that check from also allowing a newer version such as 13 be removed?

#### Alternatives or Workarounds
I found past discussion here: #45, where the recommended workaround is to manually install Java 8 ([quick link](https://github.com/expo/turtle/issues/45#issuecomment-484453067)). It seems odd that the workaround for the latest JDK not being explicitly supported is... to install a very old version? Am I reading this right? 🤔

**Comment by dsokal** [comment]
Hello again,
Unfortunately, this is not a problem with turtle-cli (nor with expo). Android SDK doesn't support other Java versions than 8. 

References:
https://developer.android.com/studio/write/java8-support
https://stackoverflow.com/a/47627603

Regarding your comment on my comment in another issue - I recommended him to install Java 8 manually because he didn't manage to install it with brew. That was a reasonable suggestion in my opinion - what do you think?

I'm closing this issue, sorry :(

**Comment by JoshuaKGoldberg** [comment]
@dsokal your messages here and that issue are very empathetic; thank you for the thoughtful responses! 

I see no fault in how you / Turtle / Expo are dealing with this weird Android restriction 😄. The _"It seems odd"_ is in reference to Android not supporting Java >8. Sorry if that came across as directed at you!

**Comment by winie** [comment]
Please reopen the issue.
The Android toolchain now also supports java 17.

**Comment by n0mer** [comment]
@winie +1
