### ISSUE TITLE
What should I cache in my CI to avoid slow `npx turtle setup:android` on every execution?

### ISSUE THREAD

**Issue by papb** [expo/turtle#258]
### Question Checklist

- [X] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [X] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [X] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject

* **What command do you have a question about?** `turtle setup:android`

#### Question Description

I use Turtle to generate an android `.apk` via CI. I am looking to speed up the generation process. What must I cache between CI executions in order to speed up the `turtle setup:android` part? Intuitively it should be possible to do this slow process only once (assuming the sdk version does not change, of course).

The exact command executed every time is: `npx turtle setup:android --sdk-version 38.0.2`

Thank you!!

**Comment by wkozyra95** [comment]
turtle stores everything in `~/.turtle/`

**Comment by papb** [comment]
@wkozyra95 Thank you! If I cache that folder and run `npx turtle setup:android --sdk-version 38.0.2` will turtle be smart enough to detect it's already in cache and skip it?

Or should I add an if-statement into my CI so that it runs `npx turtle setup:android --sdk-version 38.0.2` only if the `~/.turtle/` folder exists?

**Comment by wkozyra95** [comment]
You should use `--sdk-version 38.0.0` only the first part of the version is used. It works the same way as `sdkVersion` in app.json

The turtle will download new version if that sdk was updated in a meantime(it can change with new turtle-cli versions). If you switch between sdks, I suggest to invalidate the cache, otherwise restoring the cache might take longer than downloading it if you have few SDKs prefetched.
