### ISSUE TITLE
Support for fastlane match?

### ISSUE THREAD

**Issue by john20xdoe** [expo/turtle#54]
As an alternative to this command:
```
$ turtle build:ios \
  --team-id YOUR_TEAM_ID \
  --dist-p12-path /path/to/your/dist/cert.p12 \
  --provisioning-profile-path /path/to/your/provisioning/profile.mobileprovision
```

Could there be an option like a parameter of the match git repository, then let fastlane retrieve the common certs and profiles? something like:
```
$ turtle build:ios \
  --match-repo https://github.com/a-company/certificates
```
Reference: https://docs.fastlane.tools/actions/match/

**Comment by jonasdeprins** [comment]
+1

**Comment by dsokal** [comment]
This seems like a great idea. However, currently, we're working on a totally new build service which will eventually replace `expo build:[android|ios]` and `turtle-cli`. With the new build service, it should be possible to take advantage of fastlane (and its features) for building iOS projects.
This means we don't want to introduce new features to `turte-cli`. Stay tuned!

Because of that, I'm closing this issue, sorry.
