### ISSUE TITLE
'Missing Push Notification Entitlement' for iOS standalone build

### ISSUE THREAD

**Issue by drpancake** [expo/turtle#62]
### Environment

```
  OS: macOS Sierra 10.12.6
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found
```

### Packages

```
  expo: ^28.0.0 => 28.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4
```

### Steps to Reproduce

1. Create a standalone build using `exp build:ios` and allow Expo to manage all certificates and profiles
2. Upload the build to iTunes Connect

### Expected Behavior

The build is processed without issues and available for TestFlight submission.

### Actual Behavior

I get a warning email from iTunes Connect:

```
Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement.

If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement.

Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. 
```

**Comment by dsokal** [comment]
Yes, you have to enable Push Notification Service for App ID if you wish to use Expo. Even though you might be able to successfully upload the .ipa file to Apple, you'll most probably receive an email from Apple that your app has push notifications related key in entitlements, but that service is not enabled for the App ID. It's also possible that in future Apple won't let you upload your app if the Push Notifications Service is not enabled for the App ID.

I'm closing this issue because we plan to make a small improvement in expo-cli which will let users know if their App ID settings are not compatible with Expo projects - you can track it here - https://github.com/expo/expo-cli/issues/608

**Comment by kalyan02** [comment]
@dsokal Is this limitation specific to managed apps or even standalone/bare apps ? I am facing this issue with a bare expo app created as per instructions on react-native's docs

**Comment by AdamGerthel** [comment]
@dsokal I have the same problem as @kalyan02. Can you confirm exactly what you mean by:

> Yes, you have to enable Push Notification Service for App ID if you wish to use Expo

Do I, in an ejected app, "use Expo"? Is it just because Expo is in my package? Or that I use unimodules?

**Comment by kalyan02** [comment]
@AdamGerthel You might want to enable "Push Notofications" in capabilities in your Xcode project AND on your developer account for this particular app ID. I know this is pretty un-intuitive. In the end, I simply chose to not use expo and go via bare react native. That solved most of my issues.

**Comment by AdamGerthel** [comment]
@kalyan02 Thank god (or you)! That did it.

**Comment by bandhavya** [comment]
@AdamGerthel  @kalyan02 
I have a expo ejected project which throws push notification is not enabled on xcodebuild. How did you solve this issue ?

1.  Is it mandatory to add push notifications to my expo ejected project ? 
2. Is it mandatory to add even for bare react native project ?

**Comment by AdamGerthel** [comment]
@bandhavya I'm afraid I don't remember which changes I did - but I know that I did not have to enable push notifications in the app.

**Comment by bandhavya** [comment]
@AdamGerthel Have you Added key info.plist like in this https://stackoverflow.com/a/43974297 ?

**Comment by AdamGerthel** [comment]
@bandhavya no, and I'm not using firebase so that wouldn't make sense. I did find this: https://forums.expo.io/t/missing-push-notification-entitlement-bare-workflow/33796/2

Did you do what was suggested here? https://github.com/expo/turtle/issues/62#issuecomment-591012701 I mean, that's apparently what I did.
